# Configuration initiale du kit Faction — copiée une seule fois au premier install.
motd=§c§lFaction§r §7- PvP 1.8 entre potes
server-port=25565
max-players=30
online-mode=true
white-list=true
enforce-whitelist=true
pvp=true
difficulty=hard
gamemode=survival
hardcore=false
allow-flight=false
allow-nether=true
spawn-protection=0
view-distance=8
simulation-distance=6
max-world-size=29999984
level-name=world
level-type=minecraft\:normal
generate-structures=true
spawn-monsters=true
enable-command-block=false
network-compression-threshold=256
enforce-secure-profile=false
sync-chunk-writes=false
